#!/usr/bin/env php
<?php

set_error_handler(function ($severity, $message, $file, $line) {
    if (!(error_reporting() & $severity)) {
        return;
    }

    throw new ErrorException($message, 0, $severity, $file, $line);
});

require __DIR__.'/vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$parser = new \App\AdvCalParser();
$notifier = new \App\Notifier();

$today = date('Y-m-d');

$wins = null;
try {
    $wins = $parser->getWins($today);
} catch (\App\ParseException $ex) {
    $notifier->informAdmin($ex);
    exit;
}

$notifier->notifyCalendars($wins, $today);
